Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -3,7 +3,7 @@ name: Build and Push Docker image to AWS ECR
 on:
   push:
     branches:
-      - development
+      - main
 
 jobs:
   build-and-push:
@@ -13,12 +13,21 @@ jobs:
       uses: actions/checkout@v2
       with:
         fetch-depth: 0 # Necessary to fetch all tags and history
-################################################################
-###               SONAR CLOUD SCAN                           ###
-### Drops the build if any bugs or vulnerabilities are found.###
-###            Using the default quality gate.               ###
-###        Connected to my personal Sonar Cloud account      ###
-################################################################
+
+    - name: Verify repository clone
+      run: |
+        # Print the path where the repository is cloned
+        echo "Repository is cloned in directory: $GITHUB_WORKSPACE"
+        # List files to ensure the repository has been cloned correctly
+        echo "Listing files in the repository:"
+        ls -la $GITHUB_WORKSPACE
+        # Check if a specific file exists (e.g., Dockerfile)
+        if [ ! -f "$GITHUB_WORKSPACE/Dockerfile" ]; then
+          echo "Dockerfile not found!"
+          exit 1
+        else
+          echo "Dockerfile found."
+        fi
 
     - name: SonarCloud Scan
       uses: SonarSource/sonarcloud-github-action@master
@@ -30,13 +39,6 @@ jobs:
       run: |
         git config --global user.name 'github-actions'
         git config --global user.email 'github-actions@github.com'
-
-    
-
-################################################################
-###               DETERMINE NEXT VERSION                     ###
-###   Used for creating new releases and image tags          ###
-################################################################
 
     - name: Determine Next Version
       id: next_version
@@ -58,10 +60,6 @@ jobs:
         # Output the next version
         echo "::set-output name=tag::$NEXT_TAG"
         echo "Next version: $NEXT_TAG"
-################################################################
-###                     CREATE RELEASE                       ###
-###  Creating release with the tag from the previous step    ###
-################################################################
 
     - name: Create Release
       id: create_release
@@ -73,11 +71,6 @@ jobs:
         release_name: Release ${{ steps.next_version.outputs.tag }}
         draft: false
         prerelease: false
-
-################################################################
-###                  BUILD DOCKER IMAGE                      ###
-###         Build Docker image from the Dockefile            ###
-################################################################
 
     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v1
@@ -96,13 +89,6 @@ jobs:
         REPO_NAME="${GITHUB_REPOSITORY##*/}"
         echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
         echo "::set-output name=repo_name::$REPO_NAME"
-        
-    #- name: Convert repository name to lowercase
-    # run: |
-    #    REPO_NAME_LOWER=$(echo "$REPO_NAME" | tr '[:upper:]' '[:lower:]')
-    #   echo "REPO_NAME_LOWER=$REPO_NAME_LOWER" >> $GITHUB_ENV
-    #    echo "::set-output name=repo_name_lower::$REPO_NAME_LOWER"
-
 
     - name: Build Docker image
       env:
@@ -121,22 +107,14 @@ jobs:
           echo "Secret is set correctly"
         fi
 
-        
-        
     - name: Run Snyk to check Docker image for vulnerabilities
       uses: snyk/actions/docker@master
       env:
         SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
-        #SNYK_TOKEN: 63cb2b04-17a2-477d-97a1-3d654fdc7104
       with:
         image: ${{ env.IMAGE_NAME }}
         args: --severity-threshold=high --policy-path=.snyk
       continue-on-error: false
-
-###########################################################
-###                  PUSH IMAGE TO ECR                  ###
-###     Tag Docker image as "latest" and push to ECR    ###
-########################################################### 
 
     - name: Push Docker image to Amazon ECR
       env:
@@ -150,3 +128,35 @@ jobs:
         docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
         # Push the latest tag
         docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
+
+    - name: Deploy to EC2
+      env:
+        EC2_PEM_KEY: ${{ secrets.EC2_PEM_KEY }}
+        EC2_HOST: ${{ secrets.EC2_HOST }}
+        EC2_USER: ${{ secrets.EC2_USER }}
+        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+        ECR_REPOSITORY: counter-service
+        IMAGE_TAG: ${{ steps.next_version.outputs.tag }}
+      run: |
+        # Save PEM key to file and set permissions
+        echo "$EC2_PEM_KEY" > ec2.pem
+        chmod 400 ec2.pem
+
+        # SSH, SCP commands
+        SSH_COMMAND="ssh -i ec2.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST"
+        SCP_COMMAND="scp -i ec2.pem -o StrictHostKeyChecking=no"
+
+        #Login to Docker registry
+        $SSH_COMMAND "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REGISTRY"
+        
+        # Copy docker-compose.yml to EC2 server
+        $SCP_COMMAND docker-compose.yml $EC2_USER@$EC2_HOST:/home/ubuntu/docker/
+        $SCP_COMMAND -r data $EC2_USER@$EC2_HOST:/home/ubuntu/docker/
+
+        $SSH_COMMAND "echo 'Listing files in the /home/ubuntu/docker/ directory:' && ls -la /home/ubuntu/docker/"
+        
+        # Pull and run the Docker container on EC2
+        $SSH_COMMAND "cd /home/ubuntu/docker/ && docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG && docker compose -f docker-compose.yml up -d --force-recreate"
+        
+        # Cleanup PEM key
+        rm -f ec2.pem
